"""
Status constants for Flov7 platform.
Defines common status values used across the platform.
"""

# Workflow Statuses
WORKFLOW_STATUS_DRAFT = "draft"
WORKFLOW_STATUS_ACTIVE = "active"
WORKFLOW_STATUS_INACTIVE = "inactive"
WORKFLOW_STATUS_ARCHIVED = "archived"

WORKFLOW_STATUSES = [
    WORKFLOW_STATUS_DRAFT,
    WORKFLOW_STATUS_ACTIVE,
    WORKFLOW_STATUS_INACTIVE,
    WORKFLOW_STATUS_ARCHIVED
]

# Workflow Execution Statuses
EXECUTION_STATUS_PENDING = "pending"
EXECUTION_STATUS_RUNNING = "running"
EXECUTION_STATUS_COMPLETED = "completed"
EXECUTION_STATUS_FAILED = "failed"

EXECUTION_STATUSES = [
    EXECUTION_STATUS_PENDING,
    EXECUTION_STATUS_RUNNING,
    EXECUTION_STATUS_COMPLETED,
    EXECUTION_STATUS_FAILED
]

# User Statuses
USER_STATUS_ACTIVE = "active"
USER_STATUS_INACTIVE = "inactive"
USER_STATUS_SUSPENDED = "suspended"

USER_STATUSES = [
    USER_STATUS_ACTIVE,
    USER_STATUS_INACTIVE,
    USER_STATUS_SUSPENDED
]

# API Key Statuses
API_KEY_STATUS_ACTIVE = "active"
API_KEY_STATUS_INACTIVE = "inactive"
API_KEY_STATUS_EXPIRED = "expired"

API_KEY_STATUSES = [
    API_KEY_STATUS_ACTIVE,
    API_KEY_STATUS_INACTIVE,
    API_KEY_STATUS_EXPIRED
]

# Deployment Statuses
DEPLOYMENT_STATUS_PENDING = "pending"
DEPLOYMENT_STATUS_DEPLOYING = "deploying"
DEPLOYMENT_STATUS_ACTIVE = "active"
DEPLOYMENT_STATUS_FAILED = "failed"

DEPLOYMENT_STATUSES = [
    DEPLOYMENT_STATUS_PENDING,
    DEPLOYMENT_STATUS_DEPLOYING,
    DEPLOYMENT_STATUS_ACTIVE,
    DEPLOYMENT_STATUS_FAILED
]

# Subscription Plans
SUBSCRIPTION_PLAN_FREE = "free"
SUBSCRIPTION_PLAN_BASIC = "basic"
SUBSCRIPTION_PLAN_PRO = "pro"
SUBSCRIPTION_PLAN_ENTERPRISE = "enterprise"

SUBSCRIPTION_PLANS = [
    SUBSCRIPTION_PLAN_FREE,
    SUBSCRIPTION_PLAN_BASIC,
    SUBSCRIPTION_PLAN_PRO,
    SUBSCRIPTION_PLAN_ENTERPRISE
]

# User Roles
USER_ROLE_USER = "user"
USER_ROLE_ADMIN = "admin"
USER_ROLE_PREMIUM = "premium"

USER_ROLES = [
    USER_ROLE_USER,
    USER_ROLE_ADMIN,
    USER_ROLE_PREMIUM
]
