version: '3.8'

services:
  # API Gateway Service
  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SERVICE_NAME=api-gateway
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ../api-gateway:/app
    networks:
      - flov7-network

  # AI Service
  ai-service:
    build:
      context: ../ai-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - SERVICE_NAME=ai-service
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ../ai-service:/app
    networks:
      - flov7-network

  # Workflow Service
  workflow-service:
    build:
      context: ../workflow-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - SERVICE_NAME=workflow-service
    env_file:
      - .env
    depends_on:
      - redis
      - temporal
    volumes:
      - ../workflow-service:/app
    networks:
      - flov7-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - flov7-network

  # Temporal Server (for workflow orchestration)
  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
      - "8233:8233"
    environment:
      - DB=postgresql
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEED_FILE=/etc/temporal/schema/postgres/v12/temporal.sql
    volumes:
      - temporal_data:/etc/temporal/data
    networks:
      - flov7-network

volumes:
  redis_data:
  temporal_data:

networks:
  flov7-network:
    driver: bridge
